id: P008176
initial_creation_type: ocr
source_metadata:
  id: bdr:W20009
  title: བོད་མི་དམངས་ཀྱིས་དབྱིན་ཇི་བཙན་འཛུལ་པར་རྒོལ་བའི་གཏམ་རྒྱུད
  author: ''
  volumes:
    bfb1cd10d79f43acb7647e897765c3b2:
      image_group_id: I1GS105581
      title: ''
      volume_number: 1
      total_pages: 212
