id: I734D3D64
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T10:57:12+00:00'
last_modified: '2022-06-09T05:01:47.583827+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W20009
  title: བོད་མི་དམངས་ཀྱིས་དབྱིན་ཇི་བཙན་འཛུལ་པར་རྒོལ་བའི་གཏམ་རྒྱུད
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    94D4:
      image_group_id: I1GS105581
      title: ''
      total_pages: 212
      order: 1
      base_file: 94D4.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
